from selenium.webdriver.common.by import By

##########################################################################################
###########################################################################################
class FormPageLocatorFields:
    email_field=(By.ID,"email")
    age_field=(By.ID,"age")
    hello_there_button=(By.ID,"submitButton")
    click_me_button=(By.ID,"imageButton")
    checkbox1=(By.ID, "checky")
    checkbox2=(By.ID, "checkedchecky")
    checkbox3=(By.ID, "disabledchecky")
    checkbox4=(By.ID, "randomly_disabled_checky")
    selectomatic_drop_down=(By.NAME, "selectomatic")
    breakfast_multi_select=(By.ID, "multi")
    foo_bar_no_select=(By.NAME, "no-select")
    select_empty_multi_list=(By.NAME,"select_empty_multiple")
    select_multi_true_list=(By.NAME,"multi_true")
    select_multi_false_list=(By.NAME,"multi_false")
    select_single_disabled_list=(By.NAME,"single_disabled")
    select_multi_disabled_list=(By.NAME,"multi_disabled")
    select_from_invisible_list=(By.ID,"invisi_select")
    select_visible_invisible_multi_select=(By.ID,"invisible_multi_select")
    select_default_list=(By.NAME,"select-default")
    select_with_spaces_list=(By.NAME,"select_with_spaces")
    select_blank_nothing_list=(By.XPATH,"/html/body/form[3]/select[13]")
    snack_cheese_radio_button=(By.ID,"cheese")
    snack_peas_radio_button=(By.ID,"peas")
    snack_cheese_n_peas_radio_button=(By.ID,"cheese_and_peas")
    snack_nothing_radio_button=(By.ID,"nothing")
    snack_disabled_nothing_radio_button=(By.ID,"randomly_disabled_nothing")
    text_cheese_like_msg=(By.ID,"cheeseLiker")
    button_click=(By.XPATH,"/html/body/form[3]/input[11]")
    cumberland_sausage_radio_button=(By.ID,"lone_disabled_selected_radio")
    text_working=(By.ID,"working")
    text_not_working=(By.ID,"notWorking")
    textarea_not_working_area=(By.ID,"notWorkingArea")
    text_input_with_text=(By.ID,"inputWithText")
    textarea_with_text=(By.ID,"withText")
    textarea_empty_textarea=(By.ID,"emptyTextArea")
    select_redirect_on_change=(By.ID,"redirect")
    text_no_type=(By.ID,"no-type")
    button_choose_file_upload=(By.ID,"upload")
    button_click_submit=(By.XPATH,"/html/body/form[5]/input[3]")
    name_text=(By.NAME,"id-name1")
    id1_text=(By.ID,"id-name1")
    id2_text=(By.ID,"id-name2")
    name2_text=(By.NAME,"id-name2")
    name_text_field=(By.XPATH,"/html/body/form[6]/input[5]")
    nameX_text=(By.XPATH,"//*[@id="nested_form"]/div/input")
    name_submit_button=(By.XPATH,"//*[@id="nested_form"]/input")
    disabled_text_element1=(By.ID,"disabledTextElement1")
    disabled_text_element2=(By.ID,"disabledTextElement2")
    disabled_submit_element_button=(By.ID,"disabledSubmitElement")
    kill_containing_iframe_button=(By.ID,"killIframe")
    label_checkbox=(By.ID,"checkbox-with-label")
    