name: SelenPyTest CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # Step 4: Syntax check and lint
      - name: Lint with flake8
        run: |
          # Show warnings but don't fail the job for now
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

      # Step 5: Run tests
      - name: Run pytest tests
        run: |
          pytest QATests --maxfail=1 --disable-warnings -v
